project47/app47/urls.py
from django.urls import path
from .import views


urlpatterns=[
    path('',views.FirstPage ),
    path('LoginPage',views.LoginPage),
    path('Patientsdata',views.DataShow),
    path('SecondPage',views.SecondPage),
    path('delete/<int:id>',views.Delete),
    path('edit/<int:id>',views.Edit),
    path('update/<int:id>',views.Update),
    path('LoginPageNurse',views.LoginPageNurse),
    path('SecondPageNurse',views.SecondPageNurse),
    path('Patientsdatanurse',views.DataShowNurse),
    path('deletenurse/<int:id>',views.DeleteNurse),
    path('editnurse/<int:id>',views.EditNurse),
    path('updatenurse/<int:id>',views.UpdateNurse),
]

project47/project47/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app47.urls'))
]

project47/app47/models.py
from django.db import models
from django.db.models import CASCADE


# Create your models here.

class a1(models.Model):
    patient_id= models.CharField(max_length=10)
    firstname=models.CharField(max_length=30)
    lastname=models.CharField(max_length=30)
    treated_for=models.CharField(max_length=100)
    # date_admitted=models.DateField(max_length=30)
    prescription=models.CharField(max_length=100)
    prescription_type = models.CharField(max_length=100)
    # expected_sign_off=models.DateField(max_length=30)
    previous_history=models.CharField(max_length=100)
    emergency_contact=models.CharField(max_length=10)
    health_insurance=models.CharField(max_length=10)

class a2(models.Model):
    patient_id = models.ForeignKey(a1,on_delete=CASCADE)
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    prescription = models.CharField(max_length=100)
    emergency_contact = models.CharField(max_length=10)
    health_insurance = models.CharField(max_length=10)

project47/app47/forms.py
from django import forms
from .models import  a1,a2
# class b1(forms.Form):
#     Email=forms.EmailField(max_length=30)
#     Password=forms.CharField(widget=forms.PasswordInput)

class b2(forms.ModelForm):
    class Meta:
        model=a1
        fields='__all__'

class b3(forms.ModelForm):
    class Meta:
        model=a2
        fields='__all__'

project47/app47/views.py
from django.shortcuts import render,redirect
from .forms import b2,b3
from .models import a1,a2
# Create your views here.


def FirstPage(request):
    return render(request,'firstpage.html')


def LoginPage(request):
    return render(request,'LoginPageIdea2.html')

'''
def LoginPage(request):
    Login=b1()
    if request.method=='POST':
        Login=b1(request.POST)
        if Login.is_valid():
            # Login.save()
            return redirect('/SecondPage')
            # print(Login.cleaned_data['Email'])
            # print(Login.cleaned_data['Password'])
    else:
        return render(request,'LoginPageIdea2.html',{'forms':Login})

'''

def SecondPage(request):
    data=b2()
    if request.method=='POST':
        data=b2(request.POST)
        if data.is_valid():
            data.save()
            return redirect('/SecondPage')

    return render(request,'Secondpage.html',{'forms':data})


def DataShow(request):
    data=a1.objects.all()
    return render(request,'PatientsDataShow.html',{'res':data})

def Delete(request,id):
    data=a1.objects.get(id=id)
    data.delete()
    return redirect('/Patientsdata')

def Edit(request,id):
    data=a1.objects.get(id=id)
    return render(request,'Edit.html',{'res':data})

def Update(request,id):
    data=a1.objects.get(id=id)
    formdata=b2(request.POST,instance=data)
    if formdata.is_valid():
        formdata.save()
        return redirect('/Patientsdata')


'''This section is for the Nurses to access the patient's data'''

def LoginPageNurse(request):
    return render(request,'LoginPageNurse.html')

'''

def LoginPageNurse(request):
    Login=b1()
    if request.method=='POST':
        Login=b1(request.POST)
        if Login.is_valid():
            # Login.save()
            return redirect('/SecondPageNurse')
            # print(Login.cleaned_data['Email'])
            # print(Login.cleaned_data['Password'])
    else:
        return render(request,'LoginPageNurse.html',{'forms':Login})
'''

def SecondPageNurse(request):
    data=b3()
    if request.method=='POST':
        data=b3(request.POST)
        if data.is_valid():
            data.save()
            return redirect('/SecondPageNurse')

    return render(request,'Secondpagenurse.html',{'forms':data})


def DataShowNurse(request):
    data=a2.objects.all()
    return render(request,'PatientsDataShowNurse.html',{'res':data})

def DeleteNurse(request,id):
    data=a2.objects.get(id=id)
    data.delete()
    return redirect('/Patientsdatanurse')

def EditNurse(request,id):
    data=a2.objects.get(id=id)
    return render(request,'EditNurse.html',{'res':data})

def UpdateNurse(request,id):
    data=a2.objects.get(id=id)
    formdata=b3(request.POST,instance=data)
    if formdata.is_valid():
        formdata.save()
        return redirect("/Patientsdatanurse")

project47/app47/templates/Edit.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Edit Patient's Data</title>
    <link rel="stylesheet" href="{% static "CSS/edit.css" %}">
</head>
<body>
<form action="/update/{{res.id}}" method="post" class="dataform">
{% csrf_token %}
<p><label for="id_patient_id" id="label1">patient_id:</label> <input type="text" name="patient_id" maxlength="10" required id="id_patient_id" value="{{res.patient_id}}" class="input1"></p>
<p><label for="id_firstname" id="label2">firstname:</label> <input type="text" name="firstname" maxlength="30" required id="id_firstname" value="{{res.firstname}}" class="input2"></p>
<p><label for="id_lastname" id="label3">lastname:</label> <input type="text" name="lastname" maxlength="30" required id="id_lastname" value="{{res.lastname}}" class="input3"></p>
<p><label for="id_treated_for" id="label4">treated_for:</label> <input type="text" name="treated_for" maxlength="100" required id="id_treated_for" value="{{res.treated_for}}" class="input4"></p>
<p><label for="id_prescription" id="label5">prescription:</label> <input type="text" name="prescription" maxlength="100" required id="id_prescription" value="{{res.prescription}}" class="input5"></p>
<p><label for="id_prescription_type" id="label6">prescription_type:</label> <input type="text" name="prescription_type" maxlength="100" required id="id_prescription_type" value="{{res.prescription_type}}" class="input6"></p>
<p><label for="id_previous_history" id="label7">previous_history:</label> <input type="text" name="previous_history" maxlength="100" required id="id_previous_history" value="{{res.previous_history}}" class="input7"></p>
<p><label for="id_emergency_contact" id="label8">emergency_contact:</label> <input type="text" name="emergency_contact" maxlength="10" required id="id_emergency_contact" value="{{res.emergency_contact}}" class="input8"></p>
<p><label for="id_health_insurance" id="label9">health_insurance:</label> <input type="text" name="health_insurance" maxlength="10" required id="id_health_insurance" value="{{res.health_insurance}}" class="input9"></p>
<button type="submit" id="button1">update</button>
</form>
</body>
</html>

project47/app47/templates/EditNurse.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Edit Patient's Data</title>
    <link rel="stylesheet" href="{% static "CSS/EditNurse.css"%}">
</head>
<body>
<form action="/updatenurse/{{res.id}}" method="post" class="dataform">
{% csrf_token %}
<p><label for="id_patient_id" id="label1">patient_id:</label> <input type="text" name="patient_id" maxlength="10" required id="id_patient_id" value="{{res.patient_id}}" class="input1"></p>
<p><label for="id_firstname" id="label2">firstname:</label> <input type="text" name="firstname" maxlength="30" required id="id_firstname" value="{{res.firstname}}" class="input2"></p>
<p><label for="id_lastname" id="label3">lastname:</label> <input type="text" name="lastname" maxlength="30" required id="id_lastname" value="{{res.lastname}}" class="input3"></p>
<!--<p><label for="id_treated_for">treated_for:</label> <input type="text" name="treated_for" maxlength="100" required id="id_treated_for" value="{{res.treated_for}}"></p>-->
<!--<p><label for="id_prescription">prescription:</label> <input type="text" name="prescription" maxlength="100" required id="id_prescription" value="{{res.prescription}}"></p>-->
<!--<p><label for="id_prescription_type">prescription_type:</label> <input type="text" name="prescription_type" maxlength="100" required id="id_prescription_type" value="{{res.prescription_type}}"></p>-->
<!--<p><label for="id_previous_history">previous_history:</label> <input type="text" name="previous_history" maxlength="100" required id="id_previous_history" value="{{res.previous_history}}"></p>-->
<p><label for="id_emergency_contact" id="label8">emergency_contact:</label> <input type="text" name="emergency_contact" maxlength="10" required id="id_emergency_contact" value="{{res.emergency_contact}}" class="input8"></p>
<p><label for="id_health_insurance" id="label9">health_insurance:</label> <input type="text" name="health_insurance" maxlength="10" required id="id_health_insurance" value="{{res.health_insurance}}" class="input9"></p>
<button type="submit" id="button1">update</button>
</form>
</body>
</html>

project47/app47/templates/LoginPage.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>LogIn</title>
    <link rel="stylesheet" href="{% static "CSS/LoginPage.css" %}">

</head>
<body>
<center>
    <form method="post" action="SecondPage" class="loginform">
    {%csrf_token%}
        <h1 id="heading1">Register or LogIn </h1>
        <div class="logininfo">
            {{forms.as_p}}
        </div>
       <input type="submit" value="LogIn" id="button1">
    </form>

</center>
</body>
</html>

project47/app47/templates/LoginPageIdea2.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>LogIn to continue</title>
    <link rel="stylesheet" href="{% static "CSS/LoginPageIdea2.css"%}">
</head>
<body>
<div class="maincontainer">
  <form method="post" action="SecondPage" class="loginform" >
      {%csrf_token%}
          <h1 id="heading1">Register or LogIn </h1>
          <div class="container">
            <div class="shape1"></div>
            <div class="shape2"></div>
            <div class="shape3">
              <label class="label1">Username</label>
              <input type="email" placeholder="Email/Username" class="input1" required>
              <br><br>
              <label class="label2">Password</label>
              <input type="password" placeholder="password" class="input2" required>
            </div>

          </div>
        <input type="submit" value="LogIn" id="button1">
  </form>
</div>

</body>
</html>

project47/app47/templates/LoginPageNurse.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>LogIn(for Nurses)</title>
    <link rel="stylesheet" href="{% static "CSS/LoginPageIdea2.css"%}">
</head>
<body>
<div class="maincontainer">
  <form method="post" action="SecondPageNurse" class="loginform">
      {%csrf_token%}
          <h1 id="heading1">Register or LogIn </h1>
          <div class="container">
            <div class="shape1"></div>
            <div class="shape2"></div>
            <div class="shape3">
              <label class="label1">Username</label>
              <input type="email" placeholder="Email/Username" class="input1" required>
              <br><br>
              <label class="label2">Password</label>
              <input type="password" placeholder="password" class="input2" required>
            </div>

          </div>
        <input type="submit" value="LogIn" id="button1">
  </form>
</div>
</body>
</html>

project47/app47/templates/PatientsDataShow.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Patient's Data</title>
    <link rel="stylesheet" href="{% static "CSS/PatientsDataShow.css" %}">
</head>
<body>
<table cellspacing="3px" cellpadding="7px" class="datatable">
    <tr id="headings">
        <th> ID </th>
        <th> PATIENT ID </th>
        <th> FIRSTNAME </th>
        <th> LASTNAME </th>
        <th> TREATED FOR </th>
<!--        <th> DATE ADMITTED </th>-->
        <th> PRESCRIPTION </th>
        <th> PRESCRIPTION TYPE </th>
<!--        <th> EXPECTED SIGN-OFF </th>-->
        <th> PREVIOUS HISTORY </th>
        <th> EMERGENCY CONTACT </th>
        <th> HEALTH INSURANCE </th>
        <th> ACTION </th>
    </tr>
   {% for i in res %}
    <tr>
        <th id="unique">{{i.id}}</th>
        <td id="patientidgiven">{{i.patient_id}}</td>
        <td id="name">{{i.firstname}}</td>
        <td id="name">{{i.lastname}}</td>
        <td id="alwaysbold">{{i.treated_for}}</td>
<!--        <td>{{i.date_admitted}}</td>-->
        <td id="givemedicine">{{i.prescription}}</td>
        <td id="medicinetype">{{i.prescription_type}}</td>
<!--        <td>{{i.expected_sign_off}}</td>-->
        <td id="alwaysbold">{{i.previous_history}}</td>
        <td id="contact">{{i.emergency_contact}}</td>
        <td id="insurance">{{i.health_insurance}}</td>

        <td id="actions"> <a href="/edit/{{i.id}}">edit</a>
        <a href="/delete/{{i.id}}">delete</a>
        </td>
    </tr>
    {% endfor %}
</table>

<form action="SecondPage">
    <button type="submit" id="button1">Home</button>
</form>
</body>
</html>

project47/app47/templates/PatientsDataShowNurse.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Patient's Data</title>
    <link rel="stylesheet" href="{% static "CSS/PatientsDataShowNurse.css"%}">
</head>
<body>
<table cellspacing="3px" cellpadding="7px" class="datatable">
    <tr id="headings">
        <th> ID </th>
        <th> PATIENT ID </th>
        <th> FIRSTNAME </th>
        <th> LASTNAME </th>
<!--        <th> TREATED FOR </th>-->
<!--        <th> DATE ADMITTED </th>-->
        <th> PRESCRIPTION </th>
<!--        <th> PRESCRIPTION TYPE </th>-->
<!--        <th> EXPECTED SIGN-OFF </th>-->
<!--        <th> PREVIOUS HISTORY </th>-->
        <th> EMERGENCY CONTACT </th>
        <th> HEALTH INSURANCE </th>
        <th> ACTION </th>
    </tr>
   {% for i in res %}
    <tr>
        <th id="unique">{{i.id}}</th>
        <td id="patientidgiven">{{i.patient_id}}</td>
        <td id="name">{{i.firstname}}</td>
        <td id="name">{{i.lastname}}</td>
<!--        <td>{{i.treated_for}}</td>-->
<!--        <td>{{i.date_admitted}}</td>-->
        <td id="givemedicine">{{i.prescription}}</td>
<!--        <td>{{i.prescription_type}}</td>-->
<!--        <td>{{i.expected_sign_off}}</td>-->
<!--        <td>{{i.previous_history}}</td>-->
        <td id="contact">{{i.emergency_contact}}</td>
        <td id="insurance">{{i.health_insurance}}</td>

        <td id="actions"> <a href="/editnurse/{{i.id}}">edit</a>
        <a href="/deletenurse/{{i.id}}">delete</a>
        </td>
    </tr>
    {% endfor %}
</table>
<form action="SecondPageNurse">
    <button type="submit" id="button1">Home</button>
</form>
</body>
</html>

project47/app47/templates/Secondpage.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Doctor's Data of Patients</title>
    <link rel="stylesheet" href="{% static "CSS/SecondPage.css" %}">
</head>
<body>
<form action="SecondPage" method="post" class="dataform">
{% csrf_token %}
  {{forms.as_p}}
 <button type="submit">submit</button>
</form>


<form action="Patientsdata">
    <input type="submit" value="show" id="button2">
</form>
</body>
</html>

project47/app47/templates/Secondpagenurse.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Nurse's Data of Patients</title>
    <link rel="stylesheet" href="{% static "CSS/SecondPageNurse.css" %}">
</head>
<body>
<form action="SecondPageNurse" method="post" class="dataform">
{% csrf_token %}
  {{forms.as_p}}
 <button type="submit">submit</button>
</form>

<form action="Patientsdatanurse">
    <input type="submit" value="show" id="button2">
</form>
</body>
</html>

project47/app47/templates/firstpage.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>webpage 1</title>
    <link rel="stylesheet" href="{% static "CSS/firstpage.css" %}">
</head>
<body>
<center>
  <form action="LoginPage" method="post">
    <a href="LoginPage">
    <h1 id="heading1"> For Doctor's </h1>
    </a>
    <br>
    <br>
    <br>
    <a href="LoginPageNurse">
    <h1 id="heading2"> For Nurse/Attendant's </h1>
    </a>
    <br>
    <br>
    <br>
    <a href="LoginPage">
    <h1 id="heading3"> For Patient's </h1>
    </a>
    <div class="container">
      <a href="admin">
         <p id="para1">admin</p>
<!--      <div class="adminimage">-->
<!--        <img src="{% static "images/admin1.png"%}  ">-->
<!--      </div>-->
      </a>
    </div>
  </form>

</center>
</body>
</html>